### ISSUE TITLE
No module named 'crowd_nav.configs'

### ISSUE THREAD

**Issue by tqlblzj** [Shuijing725/CrowdNav_HEIGHT#1]
File "test.py", line 172, in <module>
    main()
  File "test.py", line 56, in main
    from crowd_nav.configs.config import Config
ModuleNotFoundError: No module named 'crowd_nav.configs'

Hi, can you provide the configs? thanks!!!

**Comment by Shuijing725** [comment]
Nice catch! I just added them in the most recent commit, please `git pull` again.

**Comment by tqlblzj** [comment]
> Nice catch! I just added them in the most recent commit, please `git pull` again.

Thanks, I have run the code successfully!!!
